//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// Nombre de archivo original:
// Fecha de generación: 21/11/2013 06:06:03 p.m.
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// No hay comentarios para ApplicationDataObjectContext en el esquema.
    /// </summary>
    public partial class ApplicationDataObjectContext : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Inicializar un nuevo objeto ApplicationDataObjectContext.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationDataObjectContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Como el espacio de nombres configurado para la referencia de este servicio
        /// en Visual Studio es diferente al indicado en el 
        /// esquema de servidor, use mapeadores de tipos para establecer asignaciones entre los dos.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("LightSwitchApplication", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("LightSwitchApplication.Implementation", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// Como el espacio de nombres configurado para la referencia de este servicio
        /// en Visual Studio es diferente al indicado en el 
        /// esquema de servidor, use mapeadores de tipos para establecer asignaciones entre los dos.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// No hay comentarios para EquipoSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Equipo> EquipoSet
        {
            get
            {
                if ((this._EquipoSet == null))
                {
                    this._EquipoSet = base.CreateQuery<Equipo>("EquipoSet");
                }
                return this._EquipoSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Equipo> _EquipoSet;
        /// <summary>
        /// No hay comentarios para UsuarioSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Usuario> UsuarioSet
        {
            get
            {
                if ((this._UsuarioSet == null))
                {
                    this._UsuarioSet = base.CreateQuery<Usuario>("UsuarioSet");
                }
                return this._UsuarioSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Usuario> _UsuarioSet;
        /// <summary>
        /// No hay comentarios para PrestamoSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Prestamo> PrestamoSet
        {
            get
            {
                if ((this._PrestamoSet == null))
                {
                    this._PrestamoSet = base.CreateQuery<Prestamo>("PrestamoSet");
                }
                return this._PrestamoSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Prestamo> _PrestamoSet;
        /// <summary>
        /// No hay comentarios para DesperfectoSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Desperfecto> DesperfectoSet
        {
            get
            {
                if ((this._DesperfectoSet == null))
                {
                    this._DesperfectoSet = base.CreateQuery<Desperfecto>("DesperfectoSet");
                }
                return this._DesperfectoSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Desperfecto> _DesperfectoSet;
        /// <summary>
        /// No hay comentarios para DesperfectoDevolucionSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DesperfectoDevolucion> DesperfectoDevolucionSet
        {
            get
            {
                if ((this._DesperfectoDevolucionSet == null))
                {
                    this._DesperfectoDevolucionSet = base.CreateQuery<DesperfectoDevolucion>("DesperfectoDevolucionSet");
                }
                return this._DesperfectoDevolucionSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DesperfectoDevolucion> _DesperfectoDevolucionSet;
        /// <summary>
        /// No hay comentarios para DevolucionSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Devolucion> DevolucionSet
        {
            get
            {
                if ((this._DevolucionSet == null))
                {
                    this._DevolucionSet = base.CreateQuery<Devolucion>("DevolucionSet");
                }
                return this._DevolucionSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Devolucion> _DevolucionSet;
        /// <summary>
        /// No hay comentarios para EquipoSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEquipoSet(Equipo equipo)
        {
            base.AddObject("EquipoSet", equipo);
        }
        /// <summary>
        /// No hay comentarios para UsuarioSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsuarioSet(Usuario usuario)
        {
            base.AddObject("UsuarioSet", usuario);
        }
        /// <summary>
        /// No hay comentarios para PrestamoSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPrestamoSet(Prestamo prestamo)
        {
            base.AddObject("PrestamoSet", prestamo);
        }
        /// <summary>
        /// No hay comentarios para DesperfectoSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDesperfectoSet(Desperfecto desperfecto)
        {
            base.AddObject("DesperfectoSet", desperfecto);
        }
        /// <summary>
        /// No hay comentarios para DesperfectoDevolucionSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDesperfectoDevolucionSet(DesperfectoDevolucion desperfectoDevolucion)
        {
            base.AddObject("DesperfectoDevolucionSet", desperfectoDevolucion);
        }
        /// <summary>
        /// No hay comentarios para DevolucionSet en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDevolucionSet(Devolucion devolucion)
        {
            base.AddObject("DevolucionSet", devolucion);
        }
    }
    /// <summary>
    /// No hay comentarios para LightSwitchApplication.Equipo en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("EquipoSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Equipo : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto Equipo.
        /// </summary>
        /// <param name="ID">Valor inicial de Id.</param>
        /// <param name="rowVersion">Valor inicial de RowVersion.</param>
        /// <param name="tipo">Valor inicial de Tipo.</param>
        /// <param name="cantidad">Valor inicial de Cantidad.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Equipo CreateEquipo(int ID, byte[] rowVersion, string tipo, int cantidad)
        {
            Equipo equipo = new Equipo();
            equipo.Id = ID;
            equipo.RowVersion = rowVersion;
            equipo.Tipo = tipo;
            equipo.Cantidad = cantidad;
            return equipo;
        }
        /// <summary>
        /// No hay comentarios para la propiedad Id en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// No hay comentarios para la propiedad RowVersion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Tipo en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Tipo
        {
            get
            {
                return this._Tipo;
            }
            set
            {
                this.OnTipoChanging(value);
                if (object.Equals(this.Tipo, value))
                {
                    return;
                }
                this._Tipo = value;
                this.OnTipoChanged();
                this.OnPropertyChanged("Tipo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Tipo;
        partial void OnTipoChanging(string value);
        partial void OnTipoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Cantidad en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Cantidad
        {
            get
            {
                return this._Cantidad;
            }
            set
            {
                this.OnCantidadChanging(value);
                if (object.Equals(this.Cantidad, value))
                {
                    return;
                }
                this._Cantidad = value;
                this.OnCantidadChanged();
                this.OnPropertyChanged("Cantidad");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Cantidad;
        partial void OnCantidadChanging(int value);
        partial void OnCantidadChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para LightSwitchApplication.Usuario en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("UsuarioSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Usuario : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="ID">Valor inicial de Id.</param>
        /// <param name="rowVersion">Valor inicial de RowVersion.</param>
        /// <param name="nombre">Valor inicial de Nombre.</param>
        /// <param name="matricula">Valor inicial de Matricula.</param>
        /// <param name="baneado">Valor inicial de Baneado.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Usuario CreateUsuario(int ID, byte[] rowVersion, string nombre, string matricula, bool baneado)
        {
            Usuario usuario = new Usuario();
            usuario.Id = ID;
            usuario.RowVersion = rowVersion;
            usuario.Nombre = nombre;
            usuario.Matricula = matricula;
            usuario.Baneado = baneado;
            return usuario;
        }
        /// <summary>
        /// No hay comentarios para la propiedad Id en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// No hay comentarios para la propiedad RowVersion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                if (object.Equals(this.Nombre, value))
                {
                    return;
                }
                this._Nombre = value;
                this.OnNombreChanged();
                this.OnPropertyChanged("Nombre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nombre;
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Matricula en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Matricula
        {
            get
            {
                return this._Matricula;
            }
            set
            {
                this.OnMatriculaChanging(value);
                if (object.Equals(this.Matricula, value))
                {
                    return;
                }
                this._Matricula = value;
                this.OnMatriculaChanged();
                this.OnPropertyChanged("Matricula");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Matricula;
        partial void OnMatriculaChanging(string value);
        partial void OnMatriculaChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Baneado en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Baneado
        {
            get
            {
                return this._Baneado;
            }
            set
            {
                this.OnBaneadoChanging(value);
                if (object.Equals(this.Baneado, value))
                {
                    return;
                }
                this._Baneado = value;
                this.OnBaneadoChanged();
                this.OnPropertyChanged("Baneado");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Baneado;
        partial void OnBaneadoChanging(bool value);
        partial void OnBaneadoChanged();
        /// <summary>
        /// No hay comentarios para PrestamoCollection en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Prestamo> PrestamoCollection
        {
            get
            {
                this.@__PrestamoCollection.EnsureValueInitialized();
                return this._PrestamoCollection;
            }
            set
            {
                this._PrestamoCollection = value;
                this.OnPropertyChanged("PrestamoCollection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Prestamo> _PrestamoCollection = new global::System.Data.Services.Client.DataServiceCollection<Prestamo>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para LightSwitchApplication.Prestamo en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PrestamoSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Prestamo : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto Prestamo.
        /// </summary>
        /// <param name="ID">Valor inicial de Id.</param>
        /// <param name="rowVersion">Valor inicial de RowVersion.</param>
        /// <param name="prestamo_Usuario">Valor inicial de Prestamo_Usuario.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Prestamo CreatePrestamo(int ID, byte[] rowVersion, int prestamo_Usuario)
        {
            Prestamo prestamo = new Prestamo();
            prestamo.Id = ID;
            prestamo.RowVersion = rowVersion;
            prestamo.Prestamo_Usuario = prestamo_Usuario;
            return prestamo;
        }
        /// <summary>
        /// No hay comentarios para la propiedad Id en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// No hay comentarios para la propiedad RowVersion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Prestamo_Usuario en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Prestamo_Usuario
        {
            get
            {
                return this._Prestamo_Usuario;
            }
            set
            {
                this.OnPrestamo_UsuarioChanging(value);
                if (object.Equals(this.Prestamo_Usuario, value))
                {
                    return;
                }
                this._Prestamo_Usuario = value;
                this.OnPrestamo_UsuarioChanged();
                this.OnPropertyChanged("Prestamo_Usuario");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Prestamo_Usuario;
        partial void OnPrestamo_UsuarioChanging(int value);
        partial void OnPrestamo_UsuarioChanged();
        /// <summary>
        /// No hay comentarios para Usuario en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Usuario Usuario
        {
            get
            {
                this.@__Usuario.EnsureValueInitialized();
                return this._Usuario;
            }
            set
            {
                Usuario previous = this.Usuario;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Usuario = null;
                    this.@__Usuario.OnValueSet();
                    previous.PrestamoCollection.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Prestamo_Usuario = value.Id;
                    }
                    else
                    {
                        this.Prestamo_Usuario = default(int);
                    }
                }
                this._Usuario = value;
                this.@__Usuario.OnValueSet();
                if ((value != null))
                {
                    value.@__PrestamoCollection.Add(this);
                }
                this.___OnPropertyChanged("Usuario");
                this.OnPropertyChanged("Usuario");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Usuario _Usuario;
        /// <summary>
        /// No hay comentarios para Devolucion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Devolucion Devolucion
        {
            get
            {
                this.@__Devolucion.EnsureValueInitialized();
                return this._Devolucion;
            }
            set
            {
                Devolucion previous = this.Devolucion;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Devolucion = null;
                    this.@__Devolucion.OnValueSet();
                    previous.Prestamo = null;
                }
                this._Devolucion = value;
                this.@__Devolucion.OnValueSet();
                if ((value != null))
                {
                    value.Prestamo = this;
                }
                this.___OnPropertyChanged("Devolucion");
                this.OnPropertyChanged("Devolucion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Devolucion _Devolucion;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para LightSwitchApplication.Desperfecto en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DesperfectoSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Desperfecto : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto Desperfecto.
        /// </summary>
        /// <param name="ID">Valor inicial de Id.</param>
        /// <param name="rowVersion">Valor inicial de RowVersion.</param>
        /// <param name="tipo">Valor inicial de Tipo.</param>
        /// <param name="monto">Valor inicial de Monto.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Desperfecto CreateDesperfecto(int ID, byte[] rowVersion, string tipo, decimal monto)
        {
            Desperfecto desperfecto = new Desperfecto();
            desperfecto.Id = ID;
            desperfecto.RowVersion = rowVersion;
            desperfecto.Tipo = tipo;
            desperfecto.Monto = monto;
            return desperfecto;
        }
        /// <summary>
        /// No hay comentarios para la propiedad Id en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// No hay comentarios para la propiedad RowVersion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Tipo en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Tipo
        {
            get
            {
                return this._Tipo;
            }
            set
            {
                this.OnTipoChanging(value);
                if (object.Equals(this.Tipo, value))
                {
                    return;
                }
                this._Tipo = value;
                this.OnTipoChanged();
                this.OnPropertyChanged("Tipo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Tipo;
        partial void OnTipoChanging(string value);
        partial void OnTipoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Monto en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Monto
        {
            get
            {
                return this._Monto;
            }
            set
            {
                this.OnMontoChanging(value);
                if (object.Equals(this.Monto, value))
                {
                    return;
                }
                this._Monto = value;
                this.OnMontoChanged();
                this.OnPropertyChanged("Monto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Monto;
        partial void OnMontoChanging(decimal value);
        partial void OnMontoChanged();
        /// <summary>
        /// No hay comentarios para DesperfectoDevolucion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<DesperfectoDevolucion> DesperfectoDevolucion
        {
            get
            {
                this.@__DesperfectoDevolucion.EnsureValueInitialized();
                return this._DesperfectoDevolucion;
            }
            set
            {
                this._DesperfectoDevolucion = value;
                this.OnPropertyChanged("DesperfectoDevolucion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<DesperfectoDevolucion> _DesperfectoDevolucion = new global::System.Data.Services.Client.DataServiceCollection<DesperfectoDevolucion>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para LightSwitchApplication.DesperfectoDevolucion en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DesperfectoDevolucionSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DesperfectoDevolucion : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto DesperfectoDevolucion.
        /// </summary>
        /// <param name="ID">Valor inicial de Id.</param>
        /// <param name="rowVersion">Valor inicial de RowVersion.</param>
        /// <param name="fecha">Valor inicial de Fecha.</param>
        /// <param name="desperfectoPrestamos_Desperfecto">Valor inicial de DesperfectoPrestamos_Desperfecto.</param>
        /// <param name="desperfectoDevolucion_Devolucion">Valor inicial de DesperfectoDevolucion_Devolucion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DesperfectoDevolucion CreateDesperfectoDevolucion(int ID, byte[] rowVersion, global::System.DateTime fecha, int desperfectoPrestamos_Desperfecto, int desperfectoDevolucion_Devolucion)
        {
            DesperfectoDevolucion desperfectoDevolucion = new DesperfectoDevolucion();
            desperfectoDevolucion.Id = ID;
            desperfectoDevolucion.RowVersion = rowVersion;
            desperfectoDevolucion.Fecha = fecha;
            desperfectoDevolucion.DesperfectoPrestamos_Desperfecto = desperfectoPrestamos_Desperfecto;
            desperfectoDevolucion.DesperfectoDevolucion_Devolucion = desperfectoDevolucion_Devolucion;
            return desperfectoDevolucion;
        }
        /// <summary>
        /// No hay comentarios para la propiedad Id en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// No hay comentarios para la propiedad RowVersion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Fecha en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                this.OnFechaChanging(value);
                if (object.Equals(this.Fecha, value))
                {
                    return;
                }
                this._Fecha = value;
                this.OnFechaChanged();
                this.OnPropertyChanged("Fecha");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
        /// <summary>
        /// No hay comentarios para la propiedad DesperfectoPrestamos_Desperfecto en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DesperfectoPrestamos_Desperfecto
        {
            get
            {
                return this._DesperfectoPrestamos_Desperfecto;
            }
            set
            {
                this.OnDesperfectoPrestamos_DesperfectoChanging(value);
                if (object.Equals(this.DesperfectoPrestamos_Desperfecto, value))
                {
                    return;
                }
                this._DesperfectoPrestamos_Desperfecto = value;
                this.OnDesperfectoPrestamos_DesperfectoChanged();
                this.OnPropertyChanged("DesperfectoPrestamos_Desperfecto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DesperfectoPrestamos_Desperfecto;
        partial void OnDesperfectoPrestamos_DesperfectoChanging(int value);
        partial void OnDesperfectoPrestamos_DesperfectoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad DesperfectoDevolucion_Devolucion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DesperfectoDevolucion_Devolucion
        {
            get
            {
                return this._DesperfectoDevolucion_Devolucion;
            }
            set
            {
                this.OnDesperfectoDevolucion_DevolucionChanging(value);
                if (object.Equals(this.DesperfectoDevolucion_Devolucion, value))
                {
                    return;
                }
                this._DesperfectoDevolucion_Devolucion = value;
                this.OnDesperfectoDevolucion_DevolucionChanged();
                this.OnPropertyChanged("DesperfectoDevolucion_Devolucion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DesperfectoDevolucion_Devolucion;
        partial void OnDesperfectoDevolucion_DevolucionChanging(int value);
        partial void OnDesperfectoDevolucion_DevolucionChanged();
        /// <summary>
        /// No hay comentarios para Desperfecto en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Desperfecto Desperfecto
        {
            get
            {
                this.@__Desperfecto.EnsureValueInitialized();
                return this._Desperfecto;
            }
            set
            {
                Desperfecto previous = this.Desperfecto;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Desperfecto = null;
                    this.@__Desperfecto.OnValueSet();
                    previous.DesperfectoDevolucion.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.DesperfectoPrestamos_Desperfecto = value.Id;
                    }
                    else
                    {
                        this.DesperfectoPrestamos_Desperfecto = default(int);
                    }
                }
                this._Desperfecto = value;
                this.@__Desperfecto.OnValueSet();
                if ((value != null))
                {
                    value.@__DesperfectoDevolucion.Add(this);
                }
                this.___OnPropertyChanged("Desperfecto");
                this.OnPropertyChanged("Desperfecto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Desperfecto _Desperfecto;
        /// <summary>
        /// No hay comentarios para Devolucion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Devolucion Devolucion
        {
            get
            {
                this.@__Devolucion.EnsureValueInitialized();
                return this._Devolucion;
            }
            set
            {
                Devolucion previous = this.Devolucion;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Devolucion = null;
                    this.@__Devolucion.OnValueSet();
                    previous.DesperfectoDevolucionCollection.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.DesperfectoDevolucion_Devolucion = value.Id;
                    }
                    else
                    {
                        this.DesperfectoDevolucion_Devolucion = default(int);
                    }
                }
                this._Devolucion = value;
                this.@__Devolucion.OnValueSet();
                if ((value != null))
                {
                    value.@__DesperfectoDevolucionCollection.Add(this);
                }
                this.___OnPropertyChanged("Devolucion");
                this.OnPropertyChanged("Devolucion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Devolucion _Devolucion;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para LightSwitchApplication.Devolucion en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DevolucionSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Devolucion : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto Devolucion.
        /// </summary>
        /// <param name="ID">Valor inicial de Id.</param>
        /// <param name="rowVersion">Valor inicial de RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Devolucion CreateDevolucion(int ID, byte[] rowVersion)
        {
            Devolucion devolucion = new Devolucion();
            devolucion.Id = ID;
            devolucion.RowVersion = rowVersion;
            return devolucion;
        }
        /// <summary>
        /// No hay comentarios para la propiedad Id en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// No hay comentarios para la propiedad RowVersion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// No hay comentarios para Prestamo en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Prestamo Prestamo
        {
            get
            {
                this.@__Prestamo.EnsureValueInitialized();
                return this._Prestamo;
            }
            set
            {
                Prestamo previous = this.Prestamo;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Prestamo = null;
                    this.@__Prestamo.OnValueSet();
                    previous.Devolucion = null;
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Id = value.Id;
                    }
                    else
                    {
                        this.Id = default(int);
                    }
                }
                this._Prestamo = value;
                this.@__Prestamo.OnValueSet();
                if ((value != null))
                {
                    value.Devolucion = this;
                }
                this.___OnPropertyChanged("Prestamo");
                this.OnPropertyChanged("Prestamo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Prestamo _Prestamo;
        /// <summary>
        /// No hay comentarios para DesperfectoDevolucionCollection en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<DesperfectoDevolucion> DesperfectoDevolucionCollection
        {
            get
            {
                this.@__DesperfectoDevolucionCollection.EnsureValueInitialized();
                return this._DesperfectoDevolucionCollection;
            }
            set
            {
                this._DesperfectoDevolucionCollection = value;
                this.OnPropertyChanged("DesperfectoDevolucionCollection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<DesperfectoDevolucion> _DesperfectoDevolucionCollection = new global::System.Data.Services.Client.DataServiceCollection<DesperfectoDevolucion>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
