//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Equipo
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Equipo :
        global::LightSwitchApplication.Equipo.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnTipoChanged()
        {
            this.___OnPropertyChanged("Tipo");
        }
        
        partial void OnCantidadChanged()
        {
            this.___OnPropertyChanged("Cantidad");
        }
        
    }
    #endregion
    
    #region Usuario
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Usuario :
        global::LightSwitchApplication.Usuario.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnNombreChanged()
        {
            this.___OnPropertyChanged("Nombre");
        }
        
        partial void OnMatriculaChanged()
        {
            this.___OnPropertyChanged("Matricula");
        }
        
        partial void OnBaneadoChanged()
        {
            this.___OnPropertyChanged("Baneado");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Usuario.DetailsClass.IImplementation.PrestamoCollection
        {
            get
            {
                return this.PrestamoCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Prestamo> __PrestamoCollection
        {
            get
            {
                if (this.___PrestamoCollection == null)
                {
                    this.___PrestamoCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Prestamo>(
                        this,
                        "PrestamoCollection",
                        () => this._PrestamoCollection,
                        e => global::System.Object.Equals(e.Prestamo_Usuario, this.Id));
                }
                return this.___PrestamoCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Prestamo> ___PrestamoCollection;
        
    }
    #endregion
    
    #region Prestamo
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Prestamo :
        global::LightSwitchApplication.Prestamo.DetailsClass.IImplementation
    {
        partial void OnPrestamo_UsuarioChanged()
        {
            this.___OnPropertyChanged("Prestamo_Usuario");
            this.___OnPropertyChanged("Usuario");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Prestamo.DetailsClass.IImplementation.Usuario
        {
            get
            {
                return this.Usuario;
            }
            set
            {
                this.Usuario = (global::LightSwitchApplication.Implementation.Usuario)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Usuario> __Usuario
        {
            get
            {
                if (this.___Usuario == null)
                {
                    this.___Usuario = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Usuario>(
                        this,
                        "Usuario",
                        new string[] { "Prestamo_Usuario" },
                        e => global::System.Object.Equals(e.Id, this.Prestamo_Usuario),
                        () => this._Usuario,
                        e => this._Usuario = e);
                }
                return this.___Usuario;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Usuario> ___Usuario;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Prestamo.DetailsClass.IImplementation.Devolucion
        {
            get
            {
                return this.Devolucion;
            }
            set
            {
                this.Devolucion = (global::LightSwitchApplication.Implementation.Devolucion)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Devolucion> __Devolucion
        {
            get
            {
                if (this.___Devolucion == null)
                {
                    this.___Devolucion = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Devolucion>(
                        this,
                        "Devolucion",
                        new string[] { "Id" },
                        e => global::System.Object.Equals(e.Id, this.Id),
                        () => this._Devolucion,
                        e => this._Devolucion = e);
                }
                return this.___Devolucion;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Devolucion> ___Devolucion;
        
    }
    #endregion
    
    #region Desperfecto
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Desperfecto :
        global::LightSwitchApplication.Desperfecto.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnTipoChanged()
        {
            this.___OnPropertyChanged("Tipo");
        }
        
        partial void OnMontoChanged()
        {
            this.___OnPropertyChanged("Monto");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Desperfecto.DetailsClass.IImplementation.DesperfectoDevolucion
        {
            get
            {
                return this.DesperfectoDevolucion;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DesperfectoDevolucion> __DesperfectoDevolucion
        {
            get
            {
                if (this.___DesperfectoDevolucion == null)
                {
                    this.___DesperfectoDevolucion = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DesperfectoDevolucion>(
                        this,
                        "DesperfectoDevolucion",
                        () => this._DesperfectoDevolucion,
                        e => global::System.Object.Equals(e.DesperfectoPrestamos_Desperfecto, this.Id));
                }
                return this.___DesperfectoDevolucion;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DesperfectoDevolucion> ___DesperfectoDevolucion;
        
    }
    #endregion
    
    #region DesperfectoDevolucion
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DesperfectoDevolucion :
        global::LightSwitchApplication.DesperfectoDevolucion.DetailsClass.IImplementation
    {
        partial void OnDesperfectoPrestamos_DesperfectoChanged()
        {
            this.___OnPropertyChanged("DesperfectoPrestamos_Desperfecto");
            this.___OnPropertyChanged("Desperfecto");
        }
        
        partial void OnDesperfectoDevolucion_DevolucionChanged()
        {
            this.___OnPropertyChanged("DesperfectoDevolucion_Devolucion");
            this.___OnPropertyChanged("Devolucion");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnFechaChanged()
        {
            this.___OnPropertyChanged("Fecha");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DesperfectoDevolucion.DetailsClass.IImplementation.Desperfecto
        {
            get
            {
                return this.Desperfecto;
            }
            set
            {
                this.Desperfecto = (global::LightSwitchApplication.Implementation.Desperfecto)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Desperfecto> __Desperfecto
        {
            get
            {
                if (this.___Desperfecto == null)
                {
                    this.___Desperfecto = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Desperfecto>(
                        this,
                        "Desperfecto",
                        new string[] { "DesperfectoPrestamos_Desperfecto" },
                        e => global::System.Object.Equals(e.Id, this.DesperfectoPrestamos_Desperfecto),
                        () => this._Desperfecto,
                        e => this._Desperfecto = e);
                }
                return this.___Desperfecto;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Desperfecto> ___Desperfecto;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DesperfectoDevolucion.DetailsClass.IImplementation.Devolucion
        {
            get
            {
                return this.Devolucion;
            }
            set
            {
                this.Devolucion = (global::LightSwitchApplication.Implementation.Devolucion)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Devolucion> __Devolucion
        {
            get
            {
                if (this.___Devolucion == null)
                {
                    this.___Devolucion = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Devolucion>(
                        this,
                        "Devolucion",
                        new string[] { "DesperfectoDevolucion_Devolucion" },
                        e => global::System.Object.Equals(e.Id, this.DesperfectoDevolucion_Devolucion),
                        () => this._Devolucion,
                        e => this._Devolucion = e);
                }
                return this.___Devolucion;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Devolucion> ___Devolucion;
        
    }
    #endregion
    
    #region Devolucion
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Devolucion :
        global::LightSwitchApplication.Devolucion.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
            this.___OnPropertyChanged("Prestamo");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Devolucion.DetailsClass.IImplementation.Prestamo
        {
            get
            {
                return this.Prestamo;
            }
            set
            {
                this.Prestamo = (global::LightSwitchApplication.Implementation.Prestamo)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Prestamo> __Prestamo
        {
            get
            {
                if (this.___Prestamo == null)
                {
                    this.___Prestamo = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Prestamo>(
                        this,
                        "Prestamo",
                        new string[] { "Id" },
                        e => global::System.Object.Equals(e.Id, this.Id),
                        () => this._Prestamo,
                        e => this._Prestamo = e);
                }
                return this.___Prestamo;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Prestamo> ___Prestamo;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Devolucion.DetailsClass.IImplementation.DesperfectoDevolucionCollection
        {
            get
            {
                return this.DesperfectoDevolucionCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DesperfectoDevolucion> __DesperfectoDevolucionCollection
        {
            get
            {
                if (this.___DesperfectoDevolucionCollection == null)
                {
                    this.___DesperfectoDevolucionCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DesperfectoDevolucion>(
                        this,
                        "DesperfectoDevolucionCollection",
                        () => this._DesperfectoDevolucionCollection,
                        e => global::System.Object.Equals(e.DesperfectoDevolucion_Devolucion, this.Id));
                }
                return this.___DesperfectoDevolucionCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DesperfectoDevolucion> ___DesperfectoDevolucionCollection;
        
    }
    #endregion
    
    #region ApplicationDataObjectContext
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationDataObjectContext
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Equipo))
            {
                return new global::LightSwitchApplication.Implementation.Equipo();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Usuario))
            {
                return new global::LightSwitchApplication.Implementation.Usuario();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Prestamo))
            {
                return new global::LightSwitchApplication.Implementation.Prestamo();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Desperfecto))
            {
                return new global::LightSwitchApplication.Implementation.Desperfecto();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DesperfectoDevolucion))
            {
                return new global::LightSwitchApplication.Implementation.DesperfectoDevolucion();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Devolucion))
            {
                return new global::LightSwitchApplication.Implementation.Devolucion();
            }
            return null;
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataObjectContext(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Equipo) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Equipo);
            }
            if (typeof(global::LightSwitchApplication.Usuario) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Usuario);
            }
            if (typeof(global::LightSwitchApplication.Prestamo) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Prestamo);
            }
            if (typeof(global::LightSwitchApplication.Desperfecto) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Desperfecto);
            }
            if (typeof(global::LightSwitchApplication.DesperfectoDevolucion) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DesperfectoDevolucion);
            }
            if (typeof(global::LightSwitchApplication.Devolucion) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Devolucion);
            }
            return null;
        }
    }
}
