//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("LightSwitchApplication", "DesperfectoDevolucion_Desperfecto", "Desperfecto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Desperfecto), "DesperfectoDevolucion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.DesperfectoDevolucion), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "Prestamo_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Usuario), "Prestamo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.Prestamo), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "Devolucion_Prestamo", "Prestamo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Prestamo), "Devolucion", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ApplicationData.Implementation.Devolucion), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "DesperfectoDevolucion_Devolucion", "Devolucion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Devolucion), "DesperfectoDevolucion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.DesperfectoDevolucion), true)]

#endregion

namespace ApplicationData.Implementation
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ApplicationDataObjectContext : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ApplicationDataObjectContext usando la cadena de conexión encontrada en la sección 'ApplicationDataObjectContext' del archivo de configuración de la aplicación.
        /// </summary>
        public ApplicationDataObjectContext() : base("name=ApplicationDataObjectContext", "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ApplicationDataObjectContext.
        /// </summary>
        public ApplicationDataObjectContext(string connectionString) : base(connectionString, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ApplicationDataObjectContext.
        /// </summary>
        public ApplicationDataObjectContext(EntityConnection connection) : base(connection, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Equipo> EquipoSet
        {
            get
            {
                if ((_EquipoSet == null))
                {
                    _EquipoSet = base.CreateObjectSet<Equipo>("EquipoSet");
                }
                return _EquipoSet;
            }
        }
        private ObjectSet<Equipo> _EquipoSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuario> UsuarioSet
        {
            get
            {
                if ((_UsuarioSet == null))
                {
                    _UsuarioSet = base.CreateObjectSet<Usuario>("UsuarioSet");
                }
                return _UsuarioSet;
            }
        }
        private ObjectSet<Usuario> _UsuarioSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Prestamo> PrestamoSet
        {
            get
            {
                if ((_PrestamoSet == null))
                {
                    _PrestamoSet = base.CreateObjectSet<Prestamo>("PrestamoSet");
                }
                return _PrestamoSet;
            }
        }
        private ObjectSet<Prestamo> _PrestamoSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Desperfecto> DesperfectoSet
        {
            get
            {
                if ((_DesperfectoSet == null))
                {
                    _DesperfectoSet = base.CreateObjectSet<Desperfecto>("DesperfectoSet");
                }
                return _DesperfectoSet;
            }
        }
        private ObjectSet<Desperfecto> _DesperfectoSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DesperfectoDevolucion> DesperfectoDevolucionSet
        {
            get
            {
                if ((_DesperfectoDevolucionSet == null))
                {
                    _DesperfectoDevolucionSet = base.CreateObjectSet<DesperfectoDevolucion>("DesperfectoDevolucionSet");
                }
                return _DesperfectoDevolucionSet;
            }
        }
        private ObjectSet<DesperfectoDevolucion> _DesperfectoDevolucionSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Devolucion> DevolucionSet
        {
            get
            {
                if ((_DevolucionSet == null))
                {
                    _DevolucionSet = base.CreateObjectSet<Devolucion>("DevolucionSet");
                }
                return _DevolucionSet;
            }
        }
        private ObjectSet<Devolucion> _DevolucionSet;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet EquipoSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEquipoSet(Equipo equipo)
        {
            base.AddObject("EquipoSet", equipo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UsuarioSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuarioSet(Usuario usuario)
        {
            base.AddObject("UsuarioSet", usuario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PrestamoSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPrestamoSet(Prestamo prestamo)
        {
            base.AddObject("PrestamoSet", prestamo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DesperfectoSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDesperfectoSet(Desperfecto desperfecto)
        {
            base.AddObject("DesperfectoSet", desperfecto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DesperfectoDevolucionSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDesperfectoDevolucionSet(DesperfectoDevolucion desperfectoDevolucion)
        {
            base.AddObject("DesperfectoDevolucionSet", desperfectoDevolucion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DevolucionSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDevolucionSet(Devolucion devolucion)
        {
            base.AddObject("DevolucionSet", devolucion);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Desperfecto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Desperfecto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Desperfecto.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="rowVersion">Valor inicial de la propiedad RowVersion.</param>
        /// <param name="tipo">Valor inicial de la propiedad Tipo.</param>
        /// <param name="monto">Valor inicial de la propiedad Monto.</param>
        public static Desperfecto CreateDesperfecto(global::System.Int32 id, global::System.Byte[] rowVersion, global::System.String tipo, global::System.Decimal monto)
        {
            Desperfecto desperfecto = new Desperfecto();
            desperfecto.Id = id;
            desperfecto.RowVersion = rowVersion;
            desperfecto.Tipo = tipo;
            desperfecto.Monto = monto;
            return desperfecto;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = value;
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = value;
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.Decimal _Monto;
        partial void OnMontoChanging(global::System.Decimal value);
        partial void OnMontoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "DesperfectoDevolucion_Desperfecto", "DesperfectoDevolucion")]
        public EntityCollection<DesperfectoDevolucion> DesperfectoDevolucion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DesperfectoDevolucion>("LightSwitchApplication.DesperfectoDevolucion_Desperfecto", "DesperfectoDevolucion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DesperfectoDevolucion>("LightSwitchApplication.DesperfectoDevolucion_Desperfecto", "DesperfectoDevolucion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="DesperfectoDevolucion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DesperfectoDevolucion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DesperfectoDevolucion.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="rowVersion">Valor inicial de la propiedad RowVersion.</param>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        /// <param name="desperfectoPrestamos_Desperfecto">Valor inicial de la propiedad DesperfectoPrestamos_Desperfecto.</param>
        /// <param name="desperfectoDevolucion_Devolucion">Valor inicial de la propiedad DesperfectoDevolucion_Devolucion.</param>
        public static DesperfectoDevolucion CreateDesperfectoDevolucion(global::System.Int32 id, global::System.Byte[] rowVersion, global::System.DateTime fecha, global::System.Int32 desperfectoPrestamos_Desperfecto, global::System.Int32 desperfectoDevolucion_Devolucion)
        {
            DesperfectoDevolucion desperfectoDevolucion = new DesperfectoDevolucion();
            desperfectoDevolucion.Id = id;
            desperfectoDevolucion.RowVersion = rowVersion;
            desperfectoDevolucion.Fecha = fecha;
            desperfectoDevolucion.DesperfectoPrestamos_Desperfecto = desperfectoPrestamos_Desperfecto;
            desperfectoDevolucion.DesperfectoDevolucion_Devolucion = desperfectoDevolucion_Devolucion;
            return desperfectoDevolucion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = value;
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DesperfectoPrestamos_Desperfecto
        {
            get
            {
                return _DesperfectoPrestamos_Desperfecto;
            }
            set
            {
                OnDesperfectoPrestamos_DesperfectoChanging(value);
                ReportPropertyChanging("DesperfectoPrestamos_Desperfecto");
                _DesperfectoPrestamos_Desperfecto = value;
                ReportPropertyChanged("DesperfectoPrestamos_Desperfecto");
                OnDesperfectoPrestamos_DesperfectoChanged();
            }
        }
        private global::System.Int32 _DesperfectoPrestamos_Desperfecto;
        partial void OnDesperfectoPrestamos_DesperfectoChanging(global::System.Int32 value);
        partial void OnDesperfectoPrestamos_DesperfectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DesperfectoDevolucion_Devolucion
        {
            get
            {
                return _DesperfectoDevolucion_Devolucion;
            }
            set
            {
                OnDesperfectoDevolucion_DevolucionChanging(value);
                ReportPropertyChanging("DesperfectoDevolucion_Devolucion");
                _DesperfectoDevolucion_Devolucion = value;
                ReportPropertyChanged("DesperfectoDevolucion_Devolucion");
                OnDesperfectoDevolucion_DevolucionChanged();
            }
        }
        private global::System.Int32 _DesperfectoDevolucion_Devolucion;
        partial void OnDesperfectoDevolucion_DevolucionChanging(global::System.Int32 value);
        partial void OnDesperfectoDevolucion_DevolucionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "DesperfectoDevolucion_Desperfecto", "Desperfecto")]
        public Desperfecto Desperfecto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Desperfecto>("LightSwitchApplication.DesperfectoDevolucion_Desperfecto", "Desperfecto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Desperfecto>("LightSwitchApplication.DesperfectoDevolucion_Desperfecto", "Desperfecto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Desperfecto> DesperfectoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Desperfecto>("LightSwitchApplication.DesperfectoDevolucion_Desperfecto", "Desperfecto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Desperfecto>("LightSwitchApplication.DesperfectoDevolucion_Desperfecto", "Desperfecto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "DesperfectoDevolucion_Devolucion", "Devolucion")]
        public Devolucion Devolucion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Devolucion>("LightSwitchApplication.DesperfectoDevolucion_Devolucion", "Devolucion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Devolucion>("LightSwitchApplication.DesperfectoDevolucion_Devolucion", "Devolucion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Devolucion> DevolucionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Devolucion>("LightSwitchApplication.DesperfectoDevolucion_Devolucion", "Devolucion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Devolucion>("LightSwitchApplication.DesperfectoDevolucion_Devolucion", "Devolucion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Devolucion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Devolucion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Devolucion.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="rowVersion">Valor inicial de la propiedad RowVersion.</param>
        public static Devolucion CreateDevolucion(global::System.Int32 id, global::System.Byte[] rowVersion)
        {
            Devolucion devolucion = new Devolucion();
            devolucion.Id = id;
            devolucion.RowVersion = rowVersion;
            return devolucion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "Devolucion_Prestamo", "Prestamo")]
        public Prestamo Prestamo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prestamo>("LightSwitchApplication.Devolucion_Prestamo", "Prestamo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prestamo>("LightSwitchApplication.Devolucion_Prestamo", "Prestamo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Prestamo> PrestamoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prestamo>("LightSwitchApplication.Devolucion_Prestamo", "Prestamo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Prestamo>("LightSwitchApplication.Devolucion_Prestamo", "Prestamo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "DesperfectoDevolucion_Devolucion", "DesperfectoDevolucion")]
        public EntityCollection<DesperfectoDevolucion> DesperfectoDevolucionCollection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DesperfectoDevolucion>("LightSwitchApplication.DesperfectoDevolucion_Devolucion", "DesperfectoDevolucion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DesperfectoDevolucion>("LightSwitchApplication.DesperfectoDevolucion_Devolucion", "DesperfectoDevolucion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Equipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Equipo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Equipo.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="rowVersion">Valor inicial de la propiedad RowVersion.</param>
        /// <param name="tipo">Valor inicial de la propiedad Tipo.</param>
        /// <param name="cantidad">Valor inicial de la propiedad Cantidad.</param>
        public static Equipo CreateEquipo(global::System.Int32 id, global::System.Byte[] rowVersion, global::System.String tipo, global::System.Int32 cantidad)
        {
            Equipo equipo = new Equipo();
            equipo.Id = id;
            equipo.RowVersion = rowVersion;
            equipo.Tipo = tipo;
            equipo.Cantidad = cantidad;
            return equipo;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = value;
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = value;
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Int32 _Cantidad;
        partial void OnCantidadChanging(global::System.Int32 value);
        partial void OnCantidadChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Prestamo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prestamo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Prestamo.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="rowVersion">Valor inicial de la propiedad RowVersion.</param>
        /// <param name="prestamo_Usuario">Valor inicial de la propiedad Prestamo_Usuario.</param>
        public static Prestamo CreatePrestamo(global::System.Int32 id, global::System.Byte[] rowVersion, global::System.Int32 prestamo_Usuario)
        {
            Prestamo prestamo = new Prestamo();
            prestamo.Id = id;
            prestamo.RowVersion = rowVersion;
            prestamo.Prestamo_Usuario = prestamo_Usuario;
            return prestamo;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Prestamo_Usuario
        {
            get
            {
                return _Prestamo_Usuario;
            }
            set
            {
                OnPrestamo_UsuarioChanging(value);
                ReportPropertyChanging("Prestamo_Usuario");
                _Prestamo_Usuario = value;
                ReportPropertyChanged("Prestamo_Usuario");
                OnPrestamo_UsuarioChanged();
            }
        }
        private global::System.Int32 _Prestamo_Usuario;
        partial void OnPrestamo_UsuarioChanging(global::System.Int32 value);
        partial void OnPrestamo_UsuarioChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "Prestamo_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("LightSwitchApplication.Prestamo_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("LightSwitchApplication.Prestamo_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("LightSwitchApplication.Prestamo_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("LightSwitchApplication.Prestamo_Usuario", "Usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "Devolucion_Prestamo", "Devolucion")]
        public Devolucion Devolucion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Devolucion>("LightSwitchApplication.Devolucion_Prestamo", "Devolucion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Devolucion>("LightSwitchApplication.Devolucion_Prestamo", "Devolucion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Devolucion> DevolucionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Devolucion>("LightSwitchApplication.Devolucion_Prestamo", "Devolucion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Devolucion>("LightSwitchApplication.Devolucion_Prestamo", "Devolucion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="rowVersion">Valor inicial de la propiedad RowVersion.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="matricula">Valor inicial de la propiedad Matricula.</param>
        /// <param name="baneado">Valor inicial de la propiedad Baneado.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.Byte[] rowVersion, global::System.String nombre, global::System.String matricula, global::System.Boolean baneado)
        {
            Usuario usuario = new Usuario();
            usuario.Id = id;
            usuario.RowVersion = rowVersion;
            usuario.Nombre = nombre;
            usuario.Matricula = matricula;
            usuario.Baneado = baneado;
            return usuario;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = value;
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Matricula
        {
            get
            {
                return _Matricula;
            }
            set
            {
                OnMatriculaChanging(value);
                ReportPropertyChanging("Matricula");
                _Matricula = value;
                ReportPropertyChanged("Matricula");
                OnMatriculaChanged();
            }
        }
        private global::System.String _Matricula;
        partial void OnMatriculaChanging(global::System.String value);
        partial void OnMatriculaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Baneado
        {
            get
            {
                return _Baneado;
            }
            set
            {
                OnBaneadoChanging(value);
                ReportPropertyChanging("Baneado");
                _Baneado = value;
                ReportPropertyChanged("Baneado");
                OnBaneadoChanged();
            }
        }
        private global::System.Boolean _Baneado;
        partial void OnBaneadoChanging(global::System.Boolean value);
        partial void OnBaneadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "Prestamo_Usuario", "Prestamo")]
        public EntityCollection<Prestamo> PrestamoCollection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Prestamo>("LightSwitchApplication.Prestamo_Usuario", "Prestamo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Prestamo>("LightSwitchApplication.Prestamo_Usuario", "Prestamo", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
