//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::ApplicationData.Implementation.ApplicationDataObjectContext>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService()
        {
            return new global::LightSwitchApplication.DataWorkspace().ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::ApplicationData.Implementation.ApplicationDataObjectContext>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::ApplicationData.Implementation.Equipo))
            {
                return new global::ApplicationData.Implementation.Equipo();
            }
            if (type == typeof(global::ApplicationData.Implementation.Usuario))
            {
                return new global::ApplicationData.Implementation.Usuario();
            }
            if (type == typeof(global::ApplicationData.Implementation.Prestamo))
            {
                return new global::ApplicationData.Implementation.Prestamo();
            }
            if (type == typeof(global::ApplicationData.Implementation.Desperfecto))
            {
                return new global::ApplicationData.Implementation.Desperfecto();
            }
            if (type == typeof(global::ApplicationData.Implementation.DesperfectoDevolucion))
            {
                return new global::ApplicationData.Implementation.DesperfectoDevolucion();
            }
            if (type == typeof(global::ApplicationData.Implementation.Devolucion))
            {
                return new global::ApplicationData.Implementation.Devolucion();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::ApplicationData.Implementation.ApplicationDataObjectContext CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::ApplicationData.Implementation.ApplicationDataObjectContext(base.GetEntityConnectionString(
                "_IntrinsicData", 
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl", 
                "System.Data.SqlClient"));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Equipo))
            {
                return new global::ApplicationData.Implementation.Equipo();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Usuario))
            {
                return new global::ApplicationData.Implementation.Usuario();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Prestamo))
            {
                return new global::ApplicationData.Implementation.Prestamo();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Desperfecto))
            {
                return new global::ApplicationData.Implementation.Desperfecto();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DesperfectoDevolucion))
            {
                return new global::ApplicationData.Implementation.DesperfectoDevolucion();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Devolucion))
            {
                return new global::ApplicationData.Implementation.Devolucion();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Equipo) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Equipo);
            }
            if (typeof(global::LightSwitchApplication.Usuario) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Usuario);
            }
            if (typeof(global::LightSwitchApplication.Prestamo) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Prestamo);
            }
            if (typeof(global::LightSwitchApplication.Desperfecto) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Desperfecto);
            }
            if (typeof(global::LightSwitchApplication.DesperfectoDevolucion) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.DesperfectoDevolucion);
            }
            if (typeof(global::LightSwitchApplication.Devolucion) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Devolucion);
            }
            return null;
        }
    }
}

namespace ApplicationData.Implementation
{

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Equipo :
        global::LightSwitchApplication.Equipo.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Usuario :
        global::LightSwitchApplication.Usuario.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Usuario.DetailsClass.IImplementation.PrestamoCollection
        {
            get
            {
                return this.PrestamoCollection;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Prestamo :
        global::LightSwitchApplication.Prestamo.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Prestamo.DetailsClass.IImplementation.Usuario
        {
            get
            {
                return this.Usuario;
            }
            set
            {
                this.Usuario = (global::ApplicationData.Implementation.Usuario)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Prestamo.DetailsClass.IImplementation.Devolucion
        {
            get
            {
                return this.Devolucion;
            }
            set
            {
                this.Devolucion = (global::ApplicationData.Implementation.Devolucion)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Devolucion");
                }
            }
        }
        
        partial void OnPrestamo_UsuarioChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Usuario");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Desperfecto :
        global::LightSwitchApplication.Desperfecto.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Desperfecto.DetailsClass.IImplementation.DesperfectoDevolucion
        {
            get
            {
                return this.DesperfectoDevolucion;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DesperfectoDevolucion :
        global::LightSwitchApplication.DesperfectoDevolucion.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DesperfectoDevolucion.DetailsClass.IImplementation.Desperfecto
        {
            get
            {
                return this.Desperfecto;
            }
            set
            {
                this.Desperfecto = (global::ApplicationData.Implementation.Desperfecto)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Desperfecto");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DesperfectoDevolucion.DetailsClass.IImplementation.Devolucion
        {
            get
            {
                return this.Devolucion;
            }
            set
            {
                this.Devolucion = (global::ApplicationData.Implementation.Devolucion)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Devolucion");
                }
            }
        }
        
        partial void OnDesperfectoPrestamos_DesperfectoChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Desperfecto");
            }
        }
        
        partial void OnDesperfectoDevolucion_DevolucionChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Devolucion");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Devolucion :
        global::LightSwitchApplication.Devolucion.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Devolucion.DetailsClass.IImplementation.Prestamo
        {
            get
            {
                return this.Prestamo;
            }
            set
            {
                this.Prestamo = (global::ApplicationData.Implementation.Prestamo)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Prestamo");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Devolucion.DetailsClass.IImplementation.DesperfectoDevolucionCollection
        {
            get
            {
                return this.DesperfectoDevolucionCollection;
            }
        }
        
        partial void OnIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Prestamo");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

