

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Devolucion : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad Devolucion.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Devolucion()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Devolucion(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Devolucion> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Devolucion.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devolucion_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devolucion_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Devolucion.DetailsClass.GetValue(this, global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Devolucion.DetailsClass.SetValue(this, global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Devolucion.DetailsClass.GetValue(this, global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Devolucion.DetailsClass.SetValue(this, global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime HoraDevolucion
        {
            get
            {
                return global::LightSwitchApplication.Devolucion.DetailsClass.GetValue(this, global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.HoraDevolucion);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HoraDevolucion_Compute(ref global::System.DateTime result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HoraDevolucion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Prestamista
        {
            get
            {
                return global::LightSwitchApplication.Devolucion.DetailsClass.GetValue(this, global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Prestamista);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestamista_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestamista_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Monto
        {
            get
            {
                return global::LightSwitchApplication.Devolucion.DetailsClass.GetValue(this, global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Monto);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Monto_Compute(ref decimal result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Monto_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Prestamo Prestamo
        {
            get
            {
                return global::LightSwitchApplication.Devolucion.DetailsClass.GetValue(this, global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Prestamo);
            }
            set
            {
                global::LightSwitchApplication.Devolucion.DetailsClass.SetValue(this, global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Prestamo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestamo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestamo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestamo_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.DesperfectoDevolucion> DesperfectoDevolucionCollection
        {
            get
            {
                return global::LightSwitchApplication.Devolucion.DetailsClass.GetValue(this, global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.DesperfectoDevolucionCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.DesperfectoDevolucion> DesperfectoDevolucionCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.Devolucion.DetailsClass.GetQuery(this, global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.DesperfectoDevolucionCollection);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Devolucion,
                global::LightSwitchApplication.Devolucion.DetailsClass,
                global::LightSwitchApplication.Devolucion.DetailsClass.IImplementation,
                global::LightSwitchApplication.Devolucion.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass>.Entry
                __DevolucionEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass>.Entry(
                    global::LightSwitchApplication.Devolucion.DetailsClass.__Devolucion_CreateNew,
                    global::LightSwitchApplication.Devolucion.DetailsClass.__Devolucion_Created,
                    global::LightSwitchApplication.Devolucion.DetailsClass.__Devolucion_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Devolucion __Devolucion_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Devolucion> es)
            {
                return new global::LightSwitchApplication.Devolucion(es);
            }
            private static void __Devolucion_Created(global::LightSwitchApplication.Devolucion e)
            {
                e.Devolucion_Created();
            }
            private static bool __Devolucion_AllowSaveWithErrors(global::LightSwitchApplication.Devolucion e)
            {
                bool result = false;
                e.Devolucion_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Devolucion.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::System.DateTime> HoraDevolucion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.HoraDevolucion) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, string> Prestamista
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Prestamista) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, decimal> Monto
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Monto) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.Prestamo> Prestamo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Prestamo) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.Prestamo>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.DesperfectoDevolucion> DesperfectoDevolucionCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.DesperfectoDevolucionCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.DesperfectoDevolucion>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Prestamo { get; set; }
                new global::System.Collections.IEnumerable DesperfectoDevolucionCollection { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Devolucion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, int>.Data> c, global::LightSwitchApplication.Devolucion.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Devolucion e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Devolucion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Devolucion.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Devolucion.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Devolucion e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Devolucion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Devolucion.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Devolucion e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Devolucion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Devolucion.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Devolucion.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Devolucion e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::System.DateTime>.Entry
                    HoraDevolucion = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::System.DateTime>.Entry(
                        "HoraDevolucion",
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._HoraDevolucion_Stub,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._HoraDevolucion_Validate,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._HoraDevolucion_ComputeValue);
                private static void _HoraDevolucion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Devolucion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Devolucion.DetailsClass d, object sf)
                {
                    c(d, ref d._HoraDevolucion, sf);
                }
                private static void _HoraDevolucion_Validate(global::LightSwitchApplication.Devolucion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.HoraDevolucion_Validate(r);
                }
                private static global::System.DateTime _HoraDevolucion_ComputeValue(global::LightSwitchApplication.Devolucion e)
                {
                    global::System.DateTime value = default(global::System.DateTime);
                    e.HoraDevolucion_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, string>.Entry
                    Prestamista = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, string>.Entry(
                        "Prestamista",
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Prestamista_Stub,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Prestamista_Validate,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Prestamista_ComputeValue);
                private static void _Prestamista_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Devolucion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, string>.Data> c, global::LightSwitchApplication.Devolucion.DetailsClass d, object sf)
                {
                    c(d, ref d._Prestamista, sf);
                }
                private static void _Prestamista_Validate(global::LightSwitchApplication.Devolucion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Prestamista_Validate(r);
                }
                private static string _Prestamista_ComputeValue(global::LightSwitchApplication.Devolucion e)
                {
                    string value = default(string);
                    e.Prestamista_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, decimal>.Entry
                    Monto = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, decimal>.Entry(
                        "Monto",
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Monto_Stub,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Monto_Validate,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Monto_ComputeValue);
                private static void _Monto_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Devolucion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Devolucion.DetailsClass d, object sf)
                {
                    c(d, ref d._Monto, sf);
                }
                private static void _Monto_Validate(global::LightSwitchApplication.Devolucion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Monto_Validate(r);
                }
                private static decimal _Monto_ComputeValue(global::LightSwitchApplication.Devolucion e)
                {
                    decimal value = default(decimal);
                    e.Monto_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.Prestamo>.Entry
                    Prestamo = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.Prestamo>.Entry(
                        "Prestamo",
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Prestamo_Stub,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Prestamo_ComputeIsReadOnly,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Prestamo_Validate,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Prestamo_GetCoreImplementationValue,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Prestamo_GetImplementationValue,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Prestamo_SetImplementationValue,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Prestamo_Refresh,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._Prestamo_OnValueChanged);
                private static void _Prestamo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Devolucion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.Prestamo>.Data> c, global::LightSwitchApplication.Devolucion.DetailsClass d, object sf)
                {
                    c(d, ref d._Prestamo, sf);
                }
                private static bool _Prestamo_ComputeIsReadOnly(global::LightSwitchApplication.Devolucion e)
                {
                    bool result = false;
                    e.Prestamo_IsReadOnly(ref result);
                    return result;
                }
                private static void _Prestamo_Validate(global::LightSwitchApplication.Devolucion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Prestamo_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Prestamo_GetCoreImplementationValue(global::LightSwitchApplication.Devolucion.DetailsClass d)
                {
                    return d.ImplementationEntity.Prestamo;
                }
                private static global::LightSwitchApplication.Prestamo _Prestamo_GetImplementationValue(global::LightSwitchApplication.Devolucion.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass>(global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Prestamo, ref d._Prestamo);
                }
                private static void _Prestamo_SetImplementationValue(global::LightSwitchApplication.Devolucion.DetailsClass d, global::LightSwitchApplication.Prestamo v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Prestamo, ref d._Prestamo, (i, ev) => i.Prestamo = ev, v);
                }
                private static void _Prestamo_Refresh(global::LightSwitchApplication.Devolucion.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.Prestamo, ref d._Prestamo);
                }
                private static void _Prestamo_OnValueChanged(global::LightSwitchApplication.Devolucion e)
                {
                    e.Prestamo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.DesperfectoDevolucion>.Entry
                    DesperfectoDevolucionCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.DesperfectoDevolucion>.Entry(
                        "DesperfectoDevolucionCollection",
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._DesperfectoDevolucionCollection_Stub,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._DesperfectoDevolucionCollection_GetReferencedEntities,
                        global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties._DesperfectoDevolucionCollection_GetEntityCollection);
                private static void _DesperfectoDevolucionCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Devolucion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.DesperfectoDevolucion>.Data> c, global::LightSwitchApplication.Devolucion.DetailsClass d, object sf)
                {
                    c(d, ref d._DesperfectoDevolucionCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.DesperfectoDevolucion> _DesperfectoDevolucionCollection_GetReferencedEntities(global::LightSwitchApplication.Devolucion.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.DesperfectoDevolucion, global::LightSwitchApplication.DesperfectoDevolucion.DetailsClass>(global::LightSwitchApplication.Devolucion.DetailsClass.PropertySetProperties.DesperfectoDevolucionCollection, ref d._DesperfectoDevolucionCollection);
                }
                private static global::System.Collections.IEnumerable _DesperfectoDevolucionCollection_GetEntityCollection(global::LightSwitchApplication.Devolucion.DetailsClass d)
                {
                    return d.ImplementationEntity.DesperfectoDevolucionCollection;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::System.DateTime>.Data _HoraDevolucion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, string>.Data _Prestamista;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, decimal>.Data _Monto;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.Prestamo>.Data _Prestamo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass, global::LightSwitchApplication.DesperfectoDevolucion>.Data _DesperfectoDevolucionCollection;
            
        }
    
        #endregion
    }
    
    #endregion
}
