

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Prestamo : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad Prestamo.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Prestamo()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Prestamo(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Prestamo> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Prestamo.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestamo_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestamo_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Prestamo.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Prestamo.DetailsClass.SetValue(this, global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Prestamo.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Prestamo.DetailsClass.SetValue(this, global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime HoraPrestamo
        {
            get
            {
                return global::LightSwitchApplication.Prestamo.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.HoraPrestamo);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HoraPrestamo_Compute(ref global::System.DateTime result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HoraPrestamo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Prestamista
        {
            get
            {
                return global::LightSwitchApplication.Prestamo.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Prestamista);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestamista_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestamista_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LimiteDevolucion
        {
            get
            {
                return global::LightSwitchApplication.Prestamo.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.LimiteDevolucion);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LimiteDevolucion_Compute(ref global::System.DateTime result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LimiteDevolucion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Usuario Usuario
        {
            get
            {
                return global::LightSwitchApplication.Prestamo.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Usuario);
            }
            set
            {
                global::LightSwitchApplication.Prestamo.DetailsClass.SetValue(this, global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Usuario, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Usuario_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Usuario_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Usuario_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Devolucion Devolucion
        {
            get
            {
                return global::LightSwitchApplication.Prestamo.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Devolucion);
            }
            set
            {
                global::LightSwitchApplication.Prestamo.DetailsClass.SetValue(this, global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Devolucion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devolucion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devolucion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devolucion_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Prestamo,
                global::LightSwitchApplication.Prestamo.DetailsClass,
                global::LightSwitchApplication.Prestamo.DetailsClass.IImplementation,
                global::LightSwitchApplication.Prestamo.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass>.Entry
                __PrestamoEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass>.Entry(
                    global::LightSwitchApplication.Prestamo.DetailsClass.__Prestamo_CreateNew,
                    global::LightSwitchApplication.Prestamo.DetailsClass.__Prestamo_Created,
                    global::LightSwitchApplication.Prestamo.DetailsClass.__Prestamo_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Prestamo __Prestamo_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Prestamo> es)
            {
                return new global::LightSwitchApplication.Prestamo(es);
            }
            private static void __Prestamo_Created(global::LightSwitchApplication.Prestamo e)
            {
                e.Prestamo_Created();
            }
            private static bool __Prestamo_AllowSaveWithErrors(global::LightSwitchApplication.Prestamo e)
            {
                bool result = false;
                e.Prestamo_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Prestamo.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime> HoraPrestamo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.HoraPrestamo) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, string> Prestamista
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Prestamista) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime> LimiteDevolucion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.LimiteDevolucion) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Usuario> Usuario
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Usuario) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Usuario>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Devolucion> Devolucion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Devolucion) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Devolucion>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Usuario { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Devolucion { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestamo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, int>.Data> c, global::LightSwitchApplication.Prestamo.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Prestamo e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Prestamo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Prestamo e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestamo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Prestamo.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Prestamo e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Prestamo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Prestamo e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime>.Entry
                    HoraPrestamo = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime>.Entry(
                        "HoraPrestamo",
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._HoraPrestamo_Stub,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._HoraPrestamo_Validate,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._HoraPrestamo_ComputeValue);
                private static void _HoraPrestamo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestamo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Prestamo.DetailsClass d, object sf)
                {
                    c(d, ref d._HoraPrestamo, sf);
                }
                private static void _HoraPrestamo_Validate(global::LightSwitchApplication.Prestamo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.HoraPrestamo_Validate(r);
                }
                private static global::System.DateTime _HoraPrestamo_ComputeValue(global::LightSwitchApplication.Prestamo e)
                {
                    global::System.DateTime value = default(global::System.DateTime);
                    e.HoraPrestamo_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, string>.Entry
                    Prestamista = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, string>.Entry(
                        "Prestamista",
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Prestamista_Stub,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Prestamista_Validate,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Prestamista_ComputeValue);
                private static void _Prestamista_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestamo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, string>.Data> c, global::LightSwitchApplication.Prestamo.DetailsClass d, object sf)
                {
                    c(d, ref d._Prestamista, sf);
                }
                private static void _Prestamista_Validate(global::LightSwitchApplication.Prestamo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Prestamista_Validate(r);
                }
                private static string _Prestamista_ComputeValue(global::LightSwitchApplication.Prestamo e)
                {
                    string value = default(string);
                    e.Prestamista_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime>.Entry
                    LimiteDevolucion = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime>.Entry(
                        "LimiteDevolucion",
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._LimiteDevolucion_Stub,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._LimiteDevolucion_Validate,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._LimiteDevolucion_ComputeValue);
                private static void _LimiteDevolucion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestamo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Prestamo.DetailsClass d, object sf)
                {
                    c(d, ref d._LimiteDevolucion, sf);
                }
                private static void _LimiteDevolucion_Validate(global::LightSwitchApplication.Prestamo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LimiteDevolucion_Validate(r);
                }
                private static global::System.DateTime _LimiteDevolucion_ComputeValue(global::LightSwitchApplication.Prestamo e)
                {
                    global::System.DateTime value = default(global::System.DateTime);
                    e.LimiteDevolucion_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Usuario>.Entry
                    Usuario = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Usuario>.Entry(
                        "Usuario",
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Usuario_Stub,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Usuario_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Usuario_Validate,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Usuario_GetCoreImplementationValue,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Usuario_GetImplementationValue,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Usuario_SetImplementationValue,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Usuario_Refresh,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Usuario_OnValueChanged);
                private static void _Usuario_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestamo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Usuario>.Data> c, global::LightSwitchApplication.Prestamo.DetailsClass d, object sf)
                {
                    c(d, ref d._Usuario, sf);
                }
                private static bool _Usuario_ComputeIsReadOnly(global::LightSwitchApplication.Prestamo e)
                {
                    bool result = false;
                    e.Usuario_IsReadOnly(ref result);
                    return result;
                }
                private static void _Usuario_Validate(global::LightSwitchApplication.Prestamo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Usuario_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Usuario_GetCoreImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass d)
                {
                    return d.ImplementationEntity.Usuario;
                }
                private static global::LightSwitchApplication.Usuario _Usuario_GetImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass>(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Usuario, ref d._Usuario);
                }
                private static void _Usuario_SetImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass d, global::LightSwitchApplication.Usuario v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Usuario, ref d._Usuario, (i, ev) => i.Usuario = ev, v);
                }
                private static void _Usuario_Refresh(global::LightSwitchApplication.Prestamo.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Usuario, ref d._Usuario);
                }
                private static void _Usuario_OnValueChanged(global::LightSwitchApplication.Prestamo e)
                {
                    e.Usuario_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Devolucion>.Entry
                    Devolucion = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Devolucion>.Entry(
                        "Devolucion",
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Devolucion_Stub,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Devolucion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Devolucion_Validate,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Devolucion_GetCoreImplementationValue,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Devolucion_GetImplementationValue,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Devolucion_SetImplementationValue,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Devolucion_Refresh,
                        global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties._Devolucion_OnValueChanged);
                private static void _Devolucion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestamo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Devolucion>.Data> c, global::LightSwitchApplication.Prestamo.DetailsClass d, object sf)
                {
                    c(d, ref d._Devolucion, sf);
                }
                private static bool _Devolucion_ComputeIsReadOnly(global::LightSwitchApplication.Prestamo e)
                {
                    bool result = false;
                    e.Devolucion_IsReadOnly(ref result);
                    return result;
                }
                private static void _Devolucion_Validate(global::LightSwitchApplication.Prestamo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Devolucion_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Devolucion_GetCoreImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass d)
                {
                    return d.ImplementationEntity.Devolucion;
                }
                private static global::LightSwitchApplication.Devolucion _Devolucion_GetImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Devolucion, global::LightSwitchApplication.Devolucion.DetailsClass>(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Devolucion, ref d._Devolucion);
                }
                private static void _Devolucion_SetImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass d, global::LightSwitchApplication.Devolucion v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Devolucion, ref d._Devolucion, (i, ev) => i.Devolucion = ev, v);
                }
                private static void _Devolucion_Refresh(global::LightSwitchApplication.Prestamo.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Prestamo.DetailsClass.PropertySetProperties.Devolucion, ref d._Devolucion);
                }
                private static void _Devolucion_OnValueChanged(global::LightSwitchApplication.Prestamo e)
                {
                    e.Devolucion_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime>.Data _HoraPrestamo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, string>.Data _Prestamista;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::System.DateTime>.Data _LimiteDevolucion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Usuario>.Data _Usuario;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass, global::LightSwitchApplication.Devolucion>.Data _Devolucion;
            
        }
    
        #endregion
    }
    
    #endregion
}
