

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Usuario : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad Usuario.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Usuario()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Usuario(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Usuario> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Usuario.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Usuario_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Usuario_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Usuario.DetailsClass.GetValue(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Usuario.DetailsClass.SetValue(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Usuario.DetailsClass.GetValue(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Usuario.DetailsClass.SetValue(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Nombre
        {
            get
            {
                return global::LightSwitchApplication.Usuario.DetailsClass.GetValue(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Nombre);
            }
            set
            {
                global::LightSwitchApplication.Usuario.DetailsClass.SetValue(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Nombre, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nombre_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nombre_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nombre_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Matricula
        {
            get
            {
                return global::LightSwitchApplication.Usuario.DetailsClass.GetValue(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Matricula);
            }
            set
            {
                global::LightSwitchApplication.Usuario.DetailsClass.SetValue(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Matricula, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Matricula_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Matricula_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Matricula_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Baneado
        {
            get
            {
                return global::LightSwitchApplication.Usuario.DetailsClass.GetValue(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Baneado);
            }
            set
            {
                global::LightSwitchApplication.Usuario.DetailsClass.SetValue(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Baneado, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Baneado_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Baneado_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Baneado_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Prestamo> PrestamoCollection
        {
            get
            {
                return global::LightSwitchApplication.Usuario.DetailsClass.GetValue(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.PrestamoCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Prestamo> PrestamoCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.Usuario.DetailsClass.GetQuery(this, global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.PrestamoCollection);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Usuario,
                global::LightSwitchApplication.Usuario.DetailsClass,
                global::LightSwitchApplication.Usuario.DetailsClass.IImplementation,
                global::LightSwitchApplication.Usuario.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass>.Entry
                __UsuarioEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass>.Entry(
                    global::LightSwitchApplication.Usuario.DetailsClass.__Usuario_CreateNew,
                    global::LightSwitchApplication.Usuario.DetailsClass.__Usuario_Created,
                    global::LightSwitchApplication.Usuario.DetailsClass.__Usuario_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Usuario __Usuario_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Usuario> es)
            {
                return new global::LightSwitchApplication.Usuario(es);
            }
            private static void __Usuario_Created(global::LightSwitchApplication.Usuario e)
            {
                e.Usuario_Created();
            }
            private static bool __Usuario_AllowSaveWithErrors(global::LightSwitchApplication.Usuario e)
            {
                bool result = false;
                e.Usuario_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Usuario.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string> Nombre
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Nombre) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string> Matricula
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Matricula) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, bool> Baneado
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.Baneado) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, global::LightSwitchApplication.Prestamo> PrestamoCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.PrestamoCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, global::LightSwitchApplication.Prestamo>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Nombre { get; set; }
                new string Matricula { get; set; }
                new bool Baneado { get; set; }
                new global::System.Collections.IEnumerable PrestamoCollection { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Usuario.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, int>.Data> c, global::LightSwitchApplication.Usuario.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Usuario e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Usuario e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Usuario.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Usuario.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Usuario e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Usuario.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Usuario.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Usuario e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Usuario e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Usuario.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Usuario.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Usuario e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string>.Entry
                    Nombre = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string>.Entry(
                        "Nombre",
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Nombre_Stub,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Nombre_ComputeIsReadOnly,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Nombre_Validate,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Nombre_GetImplementationValue,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Nombre_SetImplementationValue,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Nombre_OnValueChanged);
                private static void _Nombre_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Usuario.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string>.Data> c, global::LightSwitchApplication.Usuario.DetailsClass d, object sf)
                {
                    c(d, ref d._Nombre, sf);
                }
                private static bool _Nombre_ComputeIsReadOnly(global::LightSwitchApplication.Usuario e)
                {
                    bool result = false;
                    e.Nombre_IsReadOnly(ref result);
                    return result;
                }
                private static void _Nombre_Validate(global::LightSwitchApplication.Usuario e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Nombre_Validate(r);
                }
                private static string _Nombre_GetImplementationValue(global::LightSwitchApplication.Usuario.DetailsClass d)
                {
                    return d.ImplementationEntity.Nombre;
                }
                private static void _Nombre_SetImplementationValue(global::LightSwitchApplication.Usuario.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Nombre = v;
                }
                private static void _Nombre_OnValueChanged(global::LightSwitchApplication.Usuario e)
                {
                    e.Nombre_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string>.Entry
                    Matricula = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string>.Entry(
                        "Matricula",
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Matricula_Stub,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Matricula_ComputeIsReadOnly,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Matricula_Validate,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Matricula_GetImplementationValue,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Matricula_SetImplementationValue,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Matricula_OnValueChanged);
                private static void _Matricula_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Usuario.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string>.Data> c, global::LightSwitchApplication.Usuario.DetailsClass d, object sf)
                {
                    c(d, ref d._Matricula, sf);
                }
                private static bool _Matricula_ComputeIsReadOnly(global::LightSwitchApplication.Usuario e)
                {
                    bool result = false;
                    e.Matricula_IsReadOnly(ref result);
                    return result;
                }
                private static void _Matricula_Validate(global::LightSwitchApplication.Usuario e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Matricula_Validate(r);
                }
                private static string _Matricula_GetImplementationValue(global::LightSwitchApplication.Usuario.DetailsClass d)
                {
                    return d.ImplementationEntity.Matricula;
                }
                private static void _Matricula_SetImplementationValue(global::LightSwitchApplication.Usuario.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Matricula = v;
                }
                private static void _Matricula_OnValueChanged(global::LightSwitchApplication.Usuario e)
                {
                    e.Matricula_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, bool>.Entry
                    Baneado = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, bool>.Entry(
                        "Baneado",
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Baneado_Stub,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Baneado_ComputeIsReadOnly,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Baneado_Validate,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Baneado_GetImplementationValue,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Baneado_SetImplementationValue,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._Baneado_OnValueChanged);
                private static void _Baneado_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Usuario.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, bool>.Data> c, global::LightSwitchApplication.Usuario.DetailsClass d, object sf)
                {
                    c(d, ref d._Baneado, sf);
                }
                private static bool _Baneado_ComputeIsReadOnly(global::LightSwitchApplication.Usuario e)
                {
                    bool result = false;
                    e.Baneado_IsReadOnly(ref result);
                    return result;
                }
                private static void _Baneado_Validate(global::LightSwitchApplication.Usuario e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Baneado_Validate(r);
                }
                private static bool _Baneado_GetImplementationValue(global::LightSwitchApplication.Usuario.DetailsClass d)
                {
                    return d.ImplementationEntity.Baneado;
                }
                private static void _Baneado_SetImplementationValue(global::LightSwitchApplication.Usuario.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.Baneado = v;
                }
                private static void _Baneado_OnValueChanged(global::LightSwitchApplication.Usuario e)
                {
                    e.Baneado_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, global::LightSwitchApplication.Prestamo>.Entry
                    PrestamoCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, global::LightSwitchApplication.Prestamo>.Entry(
                        "PrestamoCollection",
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._PrestamoCollection_Stub,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._PrestamoCollection_GetReferencedEntities,
                        global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties._PrestamoCollection_GetEntityCollection);
                private static void _PrestamoCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Usuario.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, global::LightSwitchApplication.Prestamo>.Data> c, global::LightSwitchApplication.Usuario.DetailsClass d, object sf)
                {
                    c(d, ref d._PrestamoCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Prestamo> _PrestamoCollection_GetReferencedEntities(global::LightSwitchApplication.Usuario.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Prestamo, global::LightSwitchApplication.Prestamo.DetailsClass>(global::LightSwitchApplication.Usuario.DetailsClass.PropertySetProperties.PrestamoCollection, ref d._PrestamoCollection);
                }
                private static global::System.Collections.IEnumerable _PrestamoCollection_GetEntityCollection(global::LightSwitchApplication.Usuario.DetailsClass d)
                {
                    return d.ImplementationEntity.PrestamoCollection;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string>.Data _Nombre;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, string>.Data _Matricula;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, bool>.Data _Baneado;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Usuario, global::LightSwitchApplication.Usuario.DetailsClass, global::LightSwitchApplication.Prestamo>.Data _PrestamoCollection;
            
        }
    
        #endregion
    }
    
    #endregion
}
